### ISSUE TITLE
Add Python 3 compatibility

### ISSUE THREAD

**Issue by Poikilos** [celogeek/OctoPrint-ProgressBasedOnTime#2]
OctoPrint now supports Python 3 compatibility. Recently they added a plugin called "Python 3 Check" which suggests to the user to add an issue at the plugin's repo for adding Python 3 compatibilty.

**Comment by gvmturl** [comment]
Waiting for updates!

Thank you for this project!

**Comment by celogeek** [comment]
I will check this.

**Comment by celogeek** [comment]
done !

**Comment by celogeek** [comment]
I submit the changes of compat to octoprint plugin repository.
